# Generated by Django 5.0.14 on 2025-11-06 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=150, verbose_name='Especialidad Principal')),
                ('is_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('servicios', models.ManyToManyField(blank=True, related_name='especialistas_aptos', to='gestion_servicios.servicio', verbose_name='Servicios que realiza')),
                ('usuario', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Especialista')),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
                'ordering': ['usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='HorarioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Horario')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio de Jornada')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin de Jornada')),
            ],
            options={
                'verbose_name': 'Horario Base',
                'verbose_name_plural': 'Horarios Base',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_especifica', models.DateField(blank=True, null=True, verbose_name='Fecha Específica (para excepciones)')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='gestion_especialistas.especialista', verbose_name='Especialista')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialistas_asignados', to='gestion_especialistas.horariobase', verbose_name='Horario Asignado')),
            ],
            options={
                'verbose_name': 'Disponibilidad del Especialista',
                'verbose_name_plural': 'Disponibilidades de Especialistas',
                'ordering': ['especialista__usuario__first_name', 'horario__dia_semana'],
                'unique_together': {('especialista', 'horario', 'fecha_especifica')},
            },
        ),
    ]
