# Generated by Django 5.0.14 on 2025-11-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción Detallada')),
                ('duracion_minutos', models.IntegerField(default=60, verbose_name='Duración (minutos)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
