# Generated by Django 5.0.14 on 2025-11-06 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Horario')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio de Jornada')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin de Jornada')),
            ],
            options={
                'verbose_name': 'Horario de Trabajo',
                'verbose_name_plural': 'Horarios de Trabajo',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField(blank=True, null=True, verbose_name='Aplicable desde/Fecha específica')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL, verbose_name='Especialista')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialistas_disponibles', to='gestion_agenda.horario', verbose_name='Horario Asignado')),
            ],
            options={
                'verbose_name': 'Disponibilidad del Especialista',
                'verbose_name_plural': 'Disponibilidades de Especialistas',
                'unique_together': {('especialista', 'horario', 'fecha_aplicacion')},
            },
        ),
    ]
