# Generated by Django 5.0.14 on 2025-11-23 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('USUARIOS', 'Usuarios y Roles'), ('INGRESOS', 'Ingresos por Periodo'), ('FACTURACION', 'Detalle de Facturación')], max_length=50, verbose_name='Tipo de Reporte')),
                ('fecha_inicial', models.DateField(blank=True, null=True, verbose_name='Fecha Inicial')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('estado', models.CharField(choices=[('PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error de generación')], default='PROCESO', max_length=15, verbose_name='Estado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Registro de Reporte',
                'verbose_name_plural': 'Registro de Reportes',
                'permissions': [('view_reporte_registro', 'Puede ver el registro de reportes generados')],
            },
        ),
    ]
