# Generated by Django 5.0.14 on 2025-11-06 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora de la Cita')),
                ('estado', models.CharField(choices=[('PND', 'Pendiente'), ('CFM', 'Confirmada'), ('CMP', 'Completada'), ('CNC', 'Cancelada')], default='PND', max_length=3, verbose_name='Estado de la Cita')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_especialista', to=settings.AUTH_USER_MODEL, verbose_name='Especialista')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_servicios.servicio', verbose_name='Servicio Solicitado')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
