# Generated by Django 5.0.14 on 2025-10-26 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('puede_ver_usuarios', models.BooleanField(default=False, verbose_name='Puede ver usuarios')),
                ('puede_crear_usuarios', models.BooleanField(default=False, verbose_name='Puede crear usuarios')),
                ('puede_editar_usuarios', models.BooleanField(default=False, verbose_name='Puede editar usuarios')),
                ('puede_eliminar_usuarios', models.BooleanField(default=False, verbose_name='Puede eliminar usuarios')),
                ('puede_ver_reportes', models.BooleanField(default=False, verbose_name='Puede ver reportes')),
                ('puede_ver_configuracion', models.BooleanField(default=False, verbose_name='Puede ver configuración')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Acción')),
                ('tipo_accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('creacion', 'Creación de registro'), ('actualizacion', 'Actualización de registro'), ('eliminacion', 'Eliminación de registro'), ('cambio_contrasena', 'Cambio de contraseña')], max_length=20, verbose_name='Tipo de Acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Entrada de Historial',
                'verbose_name_plural': 'Historial de Usuarios',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_asignados_por_mi', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='gestion_usuarios.rol', verbose_name='Rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignación de Rol',
                'verbose_name_plural': 'Asignaciones de Roles',
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
